controllers:
  - App\Controller\FolderController
  - App\Controller\ProductController
  - App\Controller\DefaultController
  - App\Controller\UserController
  - App\Controller\AdminController
twig:
  cache: '/var/cache'
  templates_dir: '/templates'
  auto_reload: true
middlewares:
  - App\Middleware\FolderMiddleware
  - App\Middleware\UserMiddleware