controllers:
  - App\Controller\Admin\AdminController
  - App\Controller\Admin\FolderAdminController
  - App\Controller\Admin\ProductAdminController
  - App\Controller\Admin\VendorAdminController
  - App\Controller\Admin\ImageAdminController
  - App\Controller\Admin\ProductParamAdminController
  - App\Controller\Api\ImageApiController
  - App\Controller\DefaultController
  - App\Controller\UserController
  - App\Controller\ProductController
  - App\Controller\FolderController

middlewares:
  - App\Middleware\FolderMiddleware
  - App\Middleware\UserMiddleware
  - App\Middleware\SharedMiddleware
images_directory: /assets/dynamic/images/